// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'lazyImage': string;
  'lazyImageCover': string;
  'lazyImagePlaceholder': string;
}
export const cssExports: CssExports;
export default cssExports;
