// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'lazyImage': string;
  'lazyImageCover': string;
  'lazyImageLoaded': string;
  'lazyImagePlaceholder': string;
  'lazyImageSource': string;
  'lazyImageWrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
