// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'imageContainer': string;
  'imageLoader': string;
  'imageLoaderAnimate': string;
  'imageLoaderHide': string;
  'lazyImage': string;
  'lazyImageCover': string;
  'lazyImageLoaded': string;
  'lazyImageLoading': string;
  'lazyImagePlaceholder': string;
  'lazyImageSource': string;
  'lazyImageWrapper': string;
  'spin': string;
}
export const cssExports: CssExports;
export default cssExports;
