// This file is automatically generated.
// Please do not change this file!
interface CssExports {
	action: string;
	fadein: string;
	fadeout: string;
	hide: string;
	icon: string;
	show: string;
	snackbar: string;
	snackbarError: string;
	snackbarWarning: string;
	text: string;
	textError: string;
	textWarning: string;
}
export const cssExports: CssExports;
export default cssExports;
