// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ripple': string;
  'rippleDrop': string;
  'rippleEffect': string;
}
export const cssExports: CssExports;
export default cssExports;
