language: node_js
node_js: v12
cache:
  directories:
    - node_modules
addons:
  chrome: stable
before_install:
  - npm install -g @lhci/cli@0.4.x
script:
  - npm run lint:test
  - npm run build:prod
  #- npm run lighthouse:test:dev
on:
  branch: development