// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'material-icons': string;
  'materialIcons': string;
}
export const cssExports: CssExports;
export default cssExports;
