export const LOADING_EMPLOYEES = 'LOADING_EMPLOYEES';

export const GET_ALL_EMPLOYEES = 'GET_ALL_EMPLOYEES';

export const GET_EMPLOYEE = 'GET_EMPLOYEE';

export const ERROR_EVENT = 'EMPLOYEE_ERROR_EVENT';
